# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'song_list_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SongListWindow(object):
    def setupUi(self, SongListWindow):
        SongListWindow.setObjectName("SongListWindow")
        SongListWindow.resize(200, 400)
        self.centralwidget = QtWidgets.QWidget(SongListWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, -9, 201, 411))
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(200)
        SongListWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SongListWindow)
        QtCore.QMetaObject.connectSlotsByName(SongListWindow)

    def retranslateUi(self, SongListWindow):
        _translate = QtCore.QCoreApplication.translate
        SongListWindow.setWindowTitle(_translate("SongListWindow", "SongListWindow"))
